name: 创思合众
nameEn : Union Chance
author: 北京创思合众科技有限公司
copyright : Beijing Union Chance Technology Co., Ltd. 
keywords: 创思合众,北京创思合众,北京创思合众科技有限公司,签牵,人多么,点滴孝心,孝心,union,chance
description: 北京创思合众科技有限公司成立于2015年2月。定位为一家专注于互联网产品的创新型科技企业，“签牵”是公司旗下一款针对校园市场的移动社交类应用。
baseurl: 
officalWebsite : /
github: http://www.github.com/bian17888
twitter: http://www.twitter.com/clinc1
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
weichat: hk_media
tel : 010-50907051
email: haiketech@163.com
location: 北京市昌平区科星西路106号国风美唐5号楼14层
disqus: diqus-username


##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      title : "北京创思合众科技有限公司"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
