name: 创思合众
author: 北京创思合众科技有限公司
baseurl: /haike
description: Union Chance
github: http://www.github.com/bian17888
twitter: http://www.twitter.com/clinc1
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: haiketech[at]163.com
location: 40°7'19"N   116°36'3"W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
